### ISSUE TITLE
Stumped. Where is example on how to use "cookieoptions" 

### ISSUE THREAD

**Issue by geetee24** [salemdar/ngx-cookie#14]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

hi

Please posr an example on how to write a cookie with a session timeout using cookieoptions.

Thanks

**Comment by pratikthecook** [comment]
as soon as we use the CookieOption Interface it just stops working

**Comment by jthompson13** [comment]
@geetee24  I was running into issues using CookieOptions to set the expiration date but realized the problem was the date being too far into the future.
maybe this will help...

`import { CookieService, CookieOptions } from 'ngx-cookie'`
`constructor(private cookieService: CookieService) {}`
`let exp = Date(2040, 12, 21)`
`let cookieOptions = {expires: exp} as CookieOptions`
`this.cookieService.put(this.PAGE_SIZE_COOKIE, String(size), this.cookieOptions)`

@salemdar love how simple this plugs in but some quick examples on using options would be helpful

**Comment by tskweres** [comment]
Using cookie options httpOnly: true breaks ngx-cookie, the cookie doesn't get set when i use .put():

This doesn't work:
```
const cookieOptions = { httpOnly: true } as CookieOptions;
 this.cookieService.put('authToken', token, cookieOptions);
```

this works, but it's not httpOnly:
` this.cookieService.put('authToken', token);`
