### ISSUE TITLE
angular universal

### ISSUE THREAD

**Issue by BlankHrt** [salemdar/ngx-cookie#35]
document is not defined in angular universal
```javascript
 protected get cookieString(): string {
    return document.cookie || '';
  }
```

[see this](https://github.com/angular/universal-starter)

**Comment by thefliik** [comment]
Hey @BlankHrt, for this reason, you need to overwrite the `CookieService` with the `CookieBackendService` during server side rendering. I just created a PR (#39) to update the README with how to accomplish this.

Turns out, this library has all the pieces needed, already, to properly handle server side rendering.

**Comment by salemdar** [comment]
@thefliik Thanks for the PR, I just merged it 👍
